/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import main.ConnectDB.KetNoi;

/**
 *
 * @author ngomi
 */
public class ChangePass extends javax.swing.JFrame {

    /**
     * Creates new form ChangePass
     */
    private String loginName;
    public ChangePass() {
        initComponents();
    }
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }
    public String getLoginName()
    {
        return this.loginName;
    }
    public ChangePass(String loginName)
    {
        initComponents();
        setLoginName(loginName);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ChangePass_txtPassword2_reNewPass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        ChangePass_jRadioButton_showPass = new javax.swing.JRadioButton();
        ChangePass_txtPassword2_newPass = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        ChangePass_btn = new javax.swing.JButton();
        ChangePass_txtPassword2_oldPass = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jLabel1.setText("Đổi mật khẩu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(337, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        ChangePass_txtPassword2_reNewPass.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ChangePass_txtPassword2_reNewPass.setForeground(new java.awt.Color(102, 102, 102));
        ChangePass_txtPassword2_reNewPass.setBorder(null);
        ChangePass_txtPassword2_reNewPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ChangePass_txtPassword2_reNewPassFocusGained(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(45, 118, 232));
        jSeparator2.setForeground(new java.awt.Color(41, 168, 73));

        ChangePass_jRadioButton_showPass.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        ChangePass_jRadioButton_showPass.setText("Show password");
        ChangePass_jRadioButton_showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePass_jRadioButton_showPassActionPerformed(evt);
            }
        });

        ChangePass_txtPassword2_newPass.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ChangePass_txtPassword2_newPass.setForeground(new java.awt.Color(102, 102, 102));
        ChangePass_txtPassword2_newPass.setBorder(null);
        ChangePass_txtPassword2_newPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ChangePass_txtPassword2_newPassFocusGained(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(45, 118, 232));
        jSeparator3.setForeground(new java.awt.Color(41, 168, 73));

        ChangePass_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ChangePass_btn.setText("Đổi mật khẩu");
        ChangePass_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePass_btnActionPerformed(evt);
            }
        });

        ChangePass_txtPassword2_oldPass.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ChangePass_txtPassword2_oldPass.setForeground(new java.awt.Color(102, 102, 102));
        ChangePass_txtPassword2_oldPass.setBorder(null);
        ChangePass_txtPassword2_oldPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ChangePass_txtPassword2_oldPassFocusGained(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(45, 118, 232));
        jSeparator4.setForeground(new java.awt.Color(41, 168, 73));

        jLabel2.setText("Nhập mật khẩu cũ");

        jLabel3.setText("Nhập mật khẩu mới");

        jLabel7.setText("Nhập lại mật khẩu mới");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChangePass_txtPassword2_reNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangePass_txtPassword2_newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(ChangePass_txtPassword2_oldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangePass_jRadioButton_showPass)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ChangePass_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChangePass_txtPassword2_oldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(ChangePass_txtPassword2_newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChangePass_txtPassword2_reNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChangePass_jRadioButton_showPass)
                .addGap(18, 18, 18)
                .addComponent(ChangePass_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChangePass_txtPassword2_reNewPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ChangePass_txtPassword2_reNewPassFocusGained
        // TODO add your handling code here:
        ChangePass_txtPassword2_reNewPass.setText("");
    }//GEN-LAST:event_ChangePass_txtPassword2_reNewPassFocusGained

    private void ChangePass_jRadioButton_showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePass_jRadioButton_showPassActionPerformed
        if (ChangePass_jRadioButton_showPass.isSelected())
        {
            ChangePass_txtPassword2_reNewPass.setEchoChar((char) 0);
            ChangePass_txtPassword2_oldPass.setEchoChar((char) 0);
            ChangePass_txtPassword2_newPass.setEchoChar((char) 0);
        }
        else
        {
            ChangePass_txtPassword2_reNewPass.setEchoChar('*');
            ChangePass_txtPassword2_oldPass.setEchoChar('*');
            ChangePass_txtPassword2_newPass.setEchoChar('*');
        }
    }//GEN-LAST:event_ChangePass_jRadioButton_showPassActionPerformed

    private void ChangePass_txtPassword2_newPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ChangePass_txtPassword2_newPassFocusGained
        ChangePass_txtPassword2_newPass.setText("");
    }//GEN-LAST:event_ChangePass_txtPassword2_newPassFocusGained

    private void ChangePass_txtPassword2_oldPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ChangePass_txtPassword2_oldPassFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePass_txtPassword2_oldPassFocusGained
    
    private void ChangePass_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePass_btnActionPerformed
        KetNoi ketNoi = new KetNoi();
        ketNoi.Mo();
        String matKhauCu = "";
        String query = "SELECT maKhau from NHANVIEN WHERE "
                + "maNhanVien = '"+getLoginName()+"'";
        ResultSet rs = ketNoi.LayDL(query);
        try
        {
         while (rs.next())
             matKhauCu = rs.getString(1);
             System.out.println(matKhauCu);
        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
            System.out.println("Lấy mật khẩu không được rồi !");
        }
        if (matKhauCu.trim().equals(ChangePass_txtPassword2_oldPass.getText().trim()))
        {
        if (ChangePass_txtPassword2_newPass.getText().trim().equals(ChangePass_txtPassword2_reNewPass.getText().trim()))
        {
            String matKhau = ChangePass_txtPassword2_newPass.getText().trim();
            query = "UPDATE NHANVIEN \n" 
                +"SET "
                + "maKhau = '"+matKhau+"'"
                + " WHERE maNhanVien ='"+getLoginName()+"'";
            System.out.println(query);
            if (ketNoi.CapNhat(query))
        {
            JOptionPane.showMessageDialog(rootPane,"Đổi mật khẩu thành công roài đoá!");
        }
        else 
            JOptionPane.showMessageDialog(rootPane,"Sai gì rồi kìa kiểm tra lại đi!");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Nhập không đúng mật khẩu kìa nhập lại đi !!!!");
        }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu cũ sai làm ơn nhập lại!!!");
        }
        ketNoi.DongKetNoi();
    }//GEN-LAST:event_ChangePass_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangePass_btn;
    private javax.swing.JRadioButton ChangePass_jRadioButton_showPass;
    private javax.swing.JPasswordField ChangePass_txtPassword2_newPass;
    private javax.swing.JPasswordField ChangePass_txtPassword2_oldPass;
    private javax.swing.JPasswordField ChangePass_txtPassword2_reNewPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
